Write step function
julinas/rumors pull request #3
Opened 2020-06-29 16:57 UTC by cyhuang4812

2020-06-29 20:47 UTC, julinas reviewed
Please resolve the conflicts

2020-06-30 16:07 UTC, julinas requested changes

2020-06-30 16:07 UTC, julinas commented on agent.py
> +			return;
python does not take ;
(also, logically, else: return is not necessary)

2020-07-01 17:37 UTC, cyhuang4812 commented
It should be changed, but I'm not sure why I can't merge.

2020-07-02 16:37 UTC, merged